apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "storm.nimbus.fullname" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  storm.yaml: |-
    {{- include "storm.configmap.data.yaml" . }}
    storm.local.hostname: {{ template "storm.nimbus.fullname" . }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "storm.supervisor.fullname" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  storm.yaml: |-
    {{- include "storm.configmap.data.yaml" . }}
    storm.local.hostname: {{ template "storm.supervisor.fullname" . }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "storm.logging.name" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $files := .Files }}
  {{- range tuple "cluster.xml" "worker.xml" }}
  {{ . }}: |-
{{ $files.Get . | indent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "storm.ui.fullname" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  storm.yaml: |-
    {{- include "storm.configmap.data.yaml" . }} 
    storm.local.hostname: {{ template "storm.ui.fullname" . }}
