# Default values for siembol
alerting:
  deploy:
    topology:
      name: alerting-deploy-topology
      image:
        repository: gresearchdev/siembol-alerting-storm
        tag: latest
        pullPolicy: IfNotPresent
    rules:
      name: alerting-deploy-rules

# disable Kafka's Zoomkeeper in favor of Storm's
storm:
  zookeeper:
    enabled: true

kafka:
  zookeeper:
    enabled: false
    # externalZookeeper.servers: "siembol-zookeeper-headless"
